package br.gov.rj.rio.cor.karttleman.controllers

import org.json4s.{ DefaultFormats, Formats }
import org.scalatra.json._
import org.scalatra._
import br.gov.rj.rio.cor.karttleman.repositories.MessageRepository._
import br.gov.rj.rio.cor.karttleman.repositories.PessoaRepository._
import br.gov.rj.rio.cor.karttleman.repositories.JobRepository._
import com.mongodb.util.JSON

class ScheduleController extends ScalatraServlet with ScalatraBase with JacksonJsonSupport {

    protected implicit val jsonFormats: Formats = DefaultFormats

    case class Message(body: String)
    case class Pessoa(nome: String)
    case class Job(nome: String)

    before() {
        contentType = formats("json")
    }

    get("/") {
        contentType = "text/html"
        """
        <p>
            Pessoas
        </p>
        <a href="/pessoas">Pessoa</a>
        """
    }

    get("/messages") {
        val messages = allMessages
        if (messages.isEmpty) {
            List(Message("Great job!"), Message("Scalatra project generated by Yeoman!"))
        } else {
            JSON.serialize(messages)
        }
    }

    get("/pessoas") {
        val pessoas = allPessoas

        if (pessoas.isEmpty) {
            List(Pessoa("André"), Pessoa("Bruno"))
        } else {
            JSON.serialize(pessoas)
        }
    }

    get("/jobs") {
        val jobs = allJobs

        if (jobs.isEmpty) {
            List(Job("Waze - Rotas"), Job("Concessionárias - CET-RIO"))
        } else {
            JSON.serialize(jobs)
        }
    }

}